accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    # path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

   
    path('students/all/',views.dashboard_students,name='students'),
    path('student/create/',views.dashboard_students_create,name='studentcreate'),
    path('student/profile/<int:id>/',views.dashboard_student_info,name='studentinfo'),
    path('student/profile/edit/<int:id>/',views.student_edit_data,name='edit'),

    
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),



]

sse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'SSE HOSTEL PORTAL ADMINISTRATION'

templates/includes/navheader_default.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href=""></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class=""></i>
								<p class="hidden-lg hidden-md"></p>
                            </a>
                        </li>

                        {% if request.user.is_superuser %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-bell"></i> <span class="badge badge-secondary" style="font-size: 14px !important;">{{ leaves.count }}</span>
                                    <b class="caret hidden-lg hidden-md"></b>
									<p class="hidden-lg hidden-md">
										<b class="caret"></b>
									</p>
                              </a>
                              
                        </li>
                        {% endif %}

                      
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
              

                             
                         <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        <i class="fa fa-user"></i> {{ request.user}}
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout'  %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login'  %}">Login</a></li>
                                {% endif %}
                                
                                <li><a href="{% url 'accounts:changepassword' %}">Change Password</a></li>
                              
                              </ul>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>

templates/includes/navheader_student_app.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed shadow">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand" href="">Dashboard </a> -->
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class=""></i>
                                <p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>

                        
                        <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Leave
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_superuser %}
                                <li><a href="{% url 'dashboard:leaveslist' %}">Pending Leaves</a></li>
                                <li><a href="{% url 'dashboard:approvedleaveslist' %}">Approved Leaves</a></li>
                                <li><a href="{% url 'dashboard:canceleaveslist' %}">Cancelled Leaves</a></li>
                                <li><a href="{% url 'dashboard:leavesrejected' %}">Rejected Leaves</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'dashboard:createleave' %}">Apply for Leave</a></li>
                                {% else %}
                                <li><a href="{% url 'dashboard:createleave' %}">Apply for Leave</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'dashboard:staffleavetable' %}">All Leaves</a></li>
                                {% endif %}
                              </ul>
                        </li>

                        {% if request.user.is_superuser and request.user.is_staff %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Users
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:register' %}">Create Users</a></li>
                                <li><a href="{% url 'accounts:users' %}">All Users</a></li>
                              </ul>
                        </li>
                        {% endif %}
                        

                        {% if request.user.is_superuser and request.user.is_staff %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Student
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'dashboard:studentcreate' %}">Add Student</a></li>
                                <li><a href="{% url 'dashboard:students' %}">All Students</a></li>
                                <li class="divider"></li>
                                
                                
                                <li><a href="{% url 'accounts:erasedusers' %}">Deleted Students</a></li>
                              </ul>
                        </li>
                        {% endif %}

                        


                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        

                        <li class="dropdown">
                              <a href="" class="dropdown-toggle refresh-page" data-toggle="dropdown" title="Refresh Current Page">
                                    <i class="pe-7s-refresh-2"></i>
                                    <b class="hidden-lg hidden-md"></b>
                                    <p class="hidden-lg hidden-md">
                                         refresh
                                    
                                    </p>
                              </a>
                        </li>

                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        <i class="fa fa-user"></i> {{ request.user}}
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout'  %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login'  %}">Login</a></li>
                                {% endif %}
                                <li><a href="{% url 'accounts:changepassword' %}">Change Password</a></li>
                                
                              </ul>
                        </li>

                        <li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>


        <style>
            .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:not(.btn):hover, .navbar-default .navbar-nav > .active > a:not(.btn):focus, .navbar-default .navbar-nav > li > a:not(.btn):hover, .navbar-default .navbar-nav > li > a:not(.btn):focus { color: #d04247 }

            .navbar-default .navbar-nav > .open > a, .navbar-default .navbar-nav > .open > a:hover, .navbar-default .navbar-nav > .open > a:focus { color:  #d04247}

            .navbar-default .navbar-nav > .dropdown > a:hover .caret, .navbar-default .navbar-nav > .dropdown > a:focus .caret { border-bottom-color:  #d04247; border-top-color:  #d04247; }

        </style>