dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

   
    path('students/all/',views.dashboard_students,name='students'),
    path('student/create/',views.dashboard_students_create,name='studentcreate'),
    path('student/profile/<int:id>/',views.dashboard_student_info,name='studentinfo'),
    path('student/profile/edit/<int:id>/',views.student_edit_data,name='edit'),

    
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),



]

sse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index_view,name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'SSE HOSTEL PORTAL ADMINISTRATION'

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from student.forms import StudentCreateForm
from leave.models import Leave
from student.models import *
from leave.forms import LeaveCreationForm


def dashboard(request):
	
	dataset = dict()
	user = request.user

	if not request.user.is_authenticated:
		return redirect('accounts:login')

	students = Student.objects.all()
	leaves = Leave.objects.all_pending_leaves()
	
	staff_leaves = Leave.objects.filter(user = user)

	
	dataset['students'] = students
	dataset['leaves'] = leaves
	
	dataset['staff_leaves'] = staff_leaves
	dataset['title'] = 'summary'
	

	return render(request,'dashboard/dashboard_index.html',dataset)




def dashboard_students(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	dataset = dict()
	departments = Department.objects.all()
	students = Student.objects.all()

	#pagination
	query = request.GET.get('search')
	if query:
		students = students.filter(
			Q(firstname__icontains = query) |
			Q(lastname__icontains = query)
		)



	paginator = Paginator(students, 10) #show 10 employee lists per page

	page = request.GET.get('page')
	students_paginated = paginator.get_page(page)



	blocked_students = Student.objects.all_blocked_students()


	return render(request,'dashboard/student_app.html',dataset)




def dashboard_students_create(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	if request.method == 'POST':
		form = StudentCreateForm(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user
			instance.title = request.POST.get('title')
			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			instance.birthday = request.POST.get('birthday')
			instance.studentid = request.POST.get('studentid')

			instance.save()

			

			return  redirect('dashboard:students')
		else:
			messages.error(request,'Trying to create dublicate students with a single user account ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('dashboard:studentcreate')


	dataset = dict()
	form = StudentCreateForm()
	dataset['form'] = form
	dataset['title'] = 'register student'
	return render(request,'dashboard/student_create.html',dataset)


def student_edit_data(request,id):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	student = get_object_or_404(Student, id = id)
	if request.method == 'POST':
		form = StudentCreateForm(request.POST or None,request.FILES or None,instance = student)
		if form.is_valid():
			instance = form.save(commit = False)

			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			
			instance.birthday = request.POST.get('birthday')


			department_id = request.POST.get('department')
			department = Department.objects.get(id = department_id)
			instance.department = department


			instance.hometown = request.POST.get('hometown')
			instance.region = request.POST.get('region')
			instance.address = request.POST.get('address')
		
			instance.studentid = request.POST.get('studentid')

			# now = datetime.datetime.now()
			# instance.created = now
			# instance.updated = now

			instance.save()
			messages.success(request,'Account Updated Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('dashboard:students')

		else:

			messages.error(request,'Error Updating account',extra_tags = 'alert alert-warning alert-dismissible show')
			return HttpResponse("Form data not valid")

	dataset = dict()
	form = StudentCreateForm(request.POST or None,request.FILES or None,instance = student)
	dataset['form'] = form
	dataset['title'] = 'edit - {0}'.format(student.get_full_name)
	return render(request,'dashboard/student_create.html',dataset)






def dashboard_student_info(request,id):
	if not request.user.is_authenticated:
		return redirect('/')
	
	student = get_object_or_404(Student, id = id)
	
	
	dataset = dict()
	dataset['student'] = student
	dataset['title'] = 'profile - {0}'.format(student.get_full_name)
	return render(request,'dashboard/student_detail.html',dataset)






# ---------------------LEAVE-------------------------------------------



def leave_creation(request):
	if not request.user.is_authenticated:
		return redirect('accounts:login')
	if request.method == 'POST':
		form = LeaveCreationForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.user
			instance.user = user
			instance.save()


			# print(instance.defaultdays)
			messages.success(request,'Leave Request Sent,wait for Admins response',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('dashboard:createleave')

		messages.error(request,'failed to Request a Leave,please check entry dates',extra_tags = 'alert alert-warning alert-dismissible show')
		return redirect('dashboard:createleave')


	dataset = dict()
	form = LeaveCreationForm()
	dataset['form'] = form
	dataset['title'] = 'Apply for Leave'
	return render(request,'dashboard/create_leave.html',dataset)
	







def leaves_list(request):
	if not (request.user.is_staff and request.user.is_superuser):
		return redirect('/')
	leaves = Leave.objects.all_pending_leaves()
	return render(request,'dashboard/leaves_recent.html',{'leave_list':leaves,'title':'leaves list - pending'})



def leaves_approved_list(request):
	if not (request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	leaves = Leave.objects.all_approved_leaves() #approved leaves -> calling model manager method
	return render(request,'dashboard/leaves_approved.html',{'leave_list':leaves,'title':'approved leave list'})



def leaves_view(request,id):
	if not (request.user.is_authenticated):
		return redirect('/')

	leave = get_object_or_404(Leave, id = id)
	print(leave.user)
	student = Student.objects.filter(user = leave.user)[0]
	print(student)
	return render(request,'dashboard/leave_detail_view.html',{'leave':leave,'student':student,'title':'{0}-{1} leave'.format(leave.user.username,leave.status)})









def approve_leave(request,id):
	if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	user = leave.user
	student = Student.objects.filter(user = user)[0]
	leave.approve_leave

	messages.error(request,'Leave successfully approved for {0}'.format(student.get_full_name),extra_tags = 'alert alert-success alert-dismissible show')
	return redirect('dashboard:userleaveview', id = id)


def cancel_leaves_list(request):
	if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leaves = Leave.objects.all_cancel_leaves()
	return render(request,'dashboard/leaves_cancel.html',{'leave_list_cancel':leaves,'title':'Cancel leave list'})



def unapprove_leave(request,id):
	if not (request.user.is_authenticated and request.user.is_superuser):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	leave.unapprove_leave
	return redirect('dashboard:leaveslist') #redirect to unapproved list




def cancel_leave(request,id):
	if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	leave.leaves_cancel

	messages.success(request,'Leave is canceled',extra_tags = 'alert alert-success alert-dismissible show')
	return redirect('dashboard:canceleaveslist')#work on redirecting to instance leave - detail view


# Current section -> here
def uncancel_leave(request,id):
	if not (request.user.is_superuser and request.user.is_authenticated):
		return redirect('/')
	leave = get_object_or_404(Leave, id = id)
	leave.status = 'pending'
	leave.is_approved = False
	leave.save()
	messages.success(request,'Leave is uncanceled,now in pending list',extra_tags = 'alert alert-success alert-dismissible show')
	return redirect('dashboard:canceleaveslist')#work on redirecting to instance leave - detail view



def leave_rejected_list(request):

	dataset = dict()
	leave = Leave.objects.all_rejected_leaves()

	dataset['leave_list_rejected'] = leave
	return render(request,'dashboard/rejected_leaves_list.html',dataset)



def reject_leave(request,id):
	dataset = dict()
	leave = get_object_or_404(Leave, id = id)
	leave.reject_leave
	messages.success(request,'Leave is rejected',extra_tags = 'alert alert-success alert-dismissible show')
	return redirect('dashboard:leavesrejected')

	# return HttpResponse(id)


def unreject_leave(request,id):
	leave = get_object_or_404(Leave, id = id)
	leave.status = 'pending'
	leave.is_approved = False
	leave.save()
	messages.success(request,'Leave is now in pending list ',extra_tags = 'alert alert-success alert-dismissible show')

	return redirect('dashboard:leavesrejected')



#  staffs leaves table user only
def view_my_leave_table(request):
	# work on the logics
	if request.user.is_authenticated:
		user = request.user
		leaves = Leave.objects.filter(user = user)

templates/dashboard/leave_detail_view.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% load crispy_forms_tags %}

 {% block navheader %}
    {% include 'includes/navheader_student_app.html' %}
 {% endblock %}



  {% block stylesheet %}
    .rounded-circle-image{
    border-radius: 50% !important;
    width:250px;
    height:250px;
  }

  .form-wrapper{
  background:#fff;
  -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);

  padding-top: 2rem;
  padding-bottom: 2rem;

}


.list-group {
  margin-top: 10px;
}

span{
  color: #6f6f6f;
  font-weight: lighter;
  font-size: 16px;
}


.list-group-item {
    position: relative;
    display: block;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid transparent;
    font-size:17px;
}

  #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

    }

    .alert-warning{
        background:#fd7b7b;
    }

    .alert-success {
        background-color: #82b72a;
    }

    .alert-success,.alert-warning{
        font-size:16px;
    }

    .employee-name-title{
    color: #3873b1;
    font-weight: 600;
    font-variant: petite-caps;
    font-size: 3.1rem !important;
  }

  span,.list-group-item > div{
  font-variant: petite-caps;
}


.panel-default>.panel-heading {
    color: #fff !important;
    background-color: #2d88a9 !important;
}

.panel-title a:hover{
  color:#e6e4e4;
}

.panel-title a:active{
  color:#e6e4e4;
}

.panel-title a:focus{
  color:#e6e4e4;
}



  {% endblock %}


  

 {% block content %}
        <section class="content">
            <section class="container-fluid">
           
                <section class="form-wrapper">
                    <section class="row">
                        <section class="col col-lg-8 col-md-12  col-sm-12">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                            <h3 class="title-h3">{{ student.get_full_name }}</h3>
                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-4 text-center">
                          <img src="{{ student.image.url}}"  class="img-fluid rounded-circle-image">
                        </section>
                        <section class="col-lg-8 col-md-12 col-sm-12">
                                    <div class="list-group" id="list-tab" role="tablist">
                                            <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Student's Name</span> <div><b>{{ student.get_full_name }}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Start Date</span> <div> <b>{{ leave.startdate }}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>End Date</span><div><b>{{ leave.enddate}}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Duration</span> <div><b>{{ leave.leave_days}}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Type</span> <div><b>{{ leave.leavetype}}</b></div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Reason</span> <div><b>{{ leave.reason}}</b></div>
                                            </a>
                                             <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Status</span> <div><b>{{ leave.status}}</b></div>
                                             </a>

                                       
                                      </div>

                        </section>
                    </section>


                             
                                  <span style="font-size: 13px;padding-left: 1rem;" class="pull-left">Created <b>{{ leave.created }}</b></span>
                              

              {% if request.user.is_superuser and request.user.is_staff %}

                    <section class="row">
                      <section class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
                        <div class="btn-group btn-group-justified">
                          {%if leave.leave_approved %}
                          <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" class="btn btn-danger" style="background-color:rgb(185, 0, 0); color: white;" name='unapprove'>Decline
                          </a>
                          {% else %}
                          <a href="{% url 'dashboard:userleaveapprove' leave.id %}" class="btn btn-success" style="background-color:green; color: white;" name='approve'>Approve
                          </a>
                          {% endif %}
                          <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-info" style="background-color:rgb(0, 142, 185); color: white;" name='cancel'>Cancel</a>
                          <a href="{% url 'dashboard:reject' leave.id %}" class="btn btn-danger" style="background-color:rgb(185, 0, 0); color: white;" name='reject'>Reject</a>  
                        </div>
                      </section>
                    </section>

              {% endif %}

                </section>

            </section> <!-- /container --> 
        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}

{% endblock %}
</script>

templates/dashboard/leaves_approved.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

 {% block navheader %}
 	{% include 'includes/navheader_student_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 width:200px;
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}

body {
	font-size:17px;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}


#stylebutton{
	background: #d04247 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#d04247;
}


.total-leaves-count p{
	font-size: 14px;
    color: #9d9d9d;
}


{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="text-shadow: 1px 0px rgba(0,0,0,0.11)">Approved Leaves</h4>
                		</div>
                		<section class="total-leaves-count">
                			{% if leave_list %}
                			<p>Total Approved Leaves - <span>{{ leave_list.count }}</span></p>
                			{% endif %}
                		</section>
                	
                		<table class="table">
							  <thead>
							    <tr>
							      <!-- <th scope="col">#</th> -->
							      <th scope="col"><b>User</b></th>
							      <th scope="col"><b>Type</b></th>
							      <th scope="col"><b>Day(s)</b></th>
							      <th scope="col"><b>Status</b></th>
							      <th scope="col"><b>Actions</b></th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for leave in leave_list %}
							    <tr>

							      <td>{{ leave.user }}</td>
							      <td>{{ leave.leavetype}}</td>
							      <td>{{ leave.leave_days }}</td>
							      <td><span class="badge badge-success" style="background-color:rgb(21, 172, 34); font-size: 14px;">{{ leave.status }}</span></td>

							      <td> 
							      	<a href="{% url 'dashboard:userleaveview' leave.id %}" style="color: #795548;">
							      	    <span>View &nbsp;</span>
							      	</a>
							      	
							        <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" style="color:#bd0404;">
							       	<span>Unapprove</span>
							        </a>

							      </td>
							    </tr>

							    {% endfor %}

							  </tbody>

						</table>
			
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

<!-- pe-7s-back   <= -->

templates/dashboard/leaves_cancel.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

 {% block navheader %}
 	{% include 'includes/navheader_student_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 width:200px;
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}

body {
	font-size:17px;
}


#stylebutton{
	background: #d04247 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#d04247;
}


.total-leaves-count p{
	font-size: 14px;
    color: #9d9d9d;
}






{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="text-shadow: 1px 0px rgba(0,0,0,0.11)">Cancelled Leaves</h4>
                		</div>

                		<section class="total-leaves-count">
                			{% if leave_list_cancel %}
                			<p>Total cancelled leaves - <span>{{ leave_list_cancel.count }}</span></p>
                			{% endif %}
                		</section>
                	
                		<table class="table">
							  <thead>
							    <tr>
							      <!-- <th scope="col">#</th> -->
							      <th scope="col"><b>User</b></th>
							      <th scope="col"><b>Type</b></th>
							      <th scope="col"><b>Day(s)</b></th>
							      <th scope="col"><b>Status</b></th>
							      <th scope="col"><b>Actions</b></th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for leave in leave_list_cancel %}
							    <tr>

							      <td>{{ leave.user }}</td>
							      <td>{{ leave.leavetype}}</td>
							      <td>{{ leave.leave_days }}</td>
							      <td>{{ leave.status }}</td>

							      <td> 
							      	<a href="{% url 'dashboard:userleaveview' leave.id %}" style="color: #795548;">
							      	    <span>View &nbsp;</span>
							      	</a>
							      	
							      	{% if not leave.is_approved %}
							      		<a href="{% url 'dashboard:userleaveuncancel' leave.id %}" style="color:#bd0404;">Undo Cancel</a>
							      	{% endif %}
							        
							      </td>
							    </tr>

							    {% endfor %}

							  </tbody>

						</table>
			
					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}


{% endblock %}
</script>

<!-- pe-7s-back   <= -->